version: '3.3'

services:
  mongu:
      container_name: ${CONTAINER_NAME}-db
      restart: on-failure
      image: mongo:4.4-focal  
      ports: 
       - "${MONGO_PORT}:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
